/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.uniempresarial.ui;

import javax.swing.JInternalFrame;

/**
 *
 * @author uestudiantes
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Productos = new javax.swing.JMenu();
        itemRegistrarPro = new javax.swing.JMenuItem();
        itemVisualizarPro = new javax.swing.JMenuItem();
        Categorias = new javax.swing.JMenu();
        itemRegistrarCat = new javax.swing.JMenuItem();
        itemVisualizarCat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });

        itemRegistrarPro.setText("Registrar producto");
        itemRegistrarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarProActionPerformed(evt);
            }
        });
        Productos.add(itemRegistrarPro);

        itemVisualizarPro.setText("Visualizar productos");
        itemVisualizarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisualizarProActionPerformed(evt);
            }
        });
        Productos.add(itemVisualizarPro);

        jMenuBar1.add(Productos);

        Categorias.setText("Categorias");

        itemRegistrarCat.setText("Registrar categoria");
        itemRegistrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarCatActionPerformed(evt);
            }
        });
        Categorias.add(itemRegistrarCat);

        itemVisualizarCat.setText("Visualizar categoria");
        itemVisualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVisualizarCatActionPerformed(evt);
            }
        });
        Categorias.add(itemVisualizarCat);

        jMenuBar1.add(Categorias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed

    }//GEN-LAST:event_ProductosActionPerformed
    
    private void cerrarVentanasAbiertas(){
        JInternalFrame[] paneles = panelPrincipal.getAllFrames();
        for (int i = 0; i < paneles.length; i++) {
            paneles[i].dispose();
        }
    }
    
    private void itemRegistrarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarProActionPerformed
        cerrarVentanasAbiertas();
        RegistroPro registro = new RegistroPro();
        panelPrincipal.add(registro);
        registro.setVisible(true);
    }//GEN-LAST:event_itemRegistrarProActionPerformed

    
    private void itemVisualizarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisualizarProActionPerformed
        cerrarVentanasAbiertas();
        VisualizarPro visualizar = new VisualizarPro();
        panelPrincipal.add(visualizar);
        visualizar.setVisible(true);
    }//GEN-LAST:event_itemVisualizarProActionPerformed

    private void itemRegistrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarCatActionPerformed
        cerrarVentanasAbiertas();
        RegistroCat registroCat = new RegistroCat();
        panelPrincipal.add(registroCat);
        registroCat.setVisible(true);
    }//GEN-LAST:event_itemRegistrarCatActionPerformed

    private void itemVisualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVisualizarCatActionPerformed
        cerrarVentanasAbiertas();
        VisualizarCat visualizar = new VisualizarCat();
        panelPrincipal.add(visualizar);
        visualizar.setVisible(true);
    }//GEN-LAST:event_itemVisualizarCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Categorias;
    private javax.swing.JMenu Productos;
    private javax.swing.JMenuItem itemRegistrarCat;
    private javax.swing.JMenuItem itemRegistrarPro;
    private javax.swing.JMenuItem itemVisualizarCat;
    private javax.swing.JMenuItem itemVisualizarPro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
